// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sandbox.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Input struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Watchdog             uint64   `protobuf:"varint,3,opt,name=watchdog,proto3" json:"watchdog,omitempty"`
	CpuShares            uint64   `protobuf:"varint,4,opt,name=cpuShares,proto3" json:"cpuShares,omitempty"`
	Memory               string   `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	MemorySwap           string   `protobuf:"bytes,6,opt,name=memorySwap,proto3" json:"memorySwap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Input) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Input) GetWatchdog() uint64 {
	if m != nil {
		return m.Watchdog
	}
	return 0
}

func (m *Input) GetCpuShares() uint64 {
	if m != nil {
		return m.CpuShares
	}
	return 0
}

func (m *Input) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *Input) GetMemorySwap() string {
	if m != nil {
		return m.MemorySwap
	}
	return ""
}

type Output struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Runtime              float64  `protobuf:"fixed64,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Output) GetRuntime() float64 {
	if m != nil {
		return m.Runtime
	}
	return 0
}

func (m *Output) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Input)(nil), "proto.Input")
	proto.RegisterType((*Output)(nil), "proto.Output")
}

func init() { proto.RegisterFile("sandbox.proto", fileDescriptor_6fddaeda1f9b863c) }

var fileDescriptor_6fddaeda1f9b863c = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x4d, 0x1c, 0x3a, 0xa2, 0x9b, 0x59, 0x20, 0xab, 0x42, 0xa8, 0xca, 0x2a, 0xab,
	0x2e, 0xe8, 0x29, 0x58, 0x21, 0x39, 0x27, 0x98, 0x26, 0x56, 0x5a, 0xa9, 0xfe, 0x91, 0x6b, 0xab,
	0x70, 0x24, 0x6e, 0x89, 0x18, 0x97, 0x94, 0x1d, 0x2b, 0xcf, 0xf7, 0xc6, 0xb2, 0xdf, 0x7b, 0xb0,
	0x3a, 0x93, 0x1b, 0xf7, 0xfe, 0x63, 0x1b, 0xa2, 0x4f, 0x1e, 0x6b, 0x3e, 0xda, 0x2f, 0x01, 0xf5,
	0x9b, 0x0b, 0x39, 0xe1, 0x1a, 0x1e, 0x4e, 0xe4, 0xa6, 0x4c, 0x93, 0x51, 0x62, 0x23, 0xba, 0xa5,
	0x9e, 0x19, 0x11, 0xaa, 0x91, 0x12, 0xa9, 0x7b, 0xd6, 0x79, 0xfe, 0xb9, 0x7f, 0xa1, 0x34, 0x1c,
	0x46, 0x3f, 0xa9, 0xc5, 0x46, 0x74, 0x95, 0x9e, 0x19, 0x9f, 0x61, 0x39, 0x84, 0xdc, 0x1f, 0x28,
	0x9a, 0xb3, 0xaa, 0x78, 0x79, 0x13, 0xf0, 0x09, 0xa4, 0x35, 0xd6, 0xc7, 0x4f, 0x55, 0xf3, 0x7b,
	0x57, 0xc2, 0x17, 0x80, 0x32, 0xf5, 0x17, 0x0a, 0x4a, 0xf2, 0xee, 0x8f, 0xd2, 0x6a, 0x90, 0xef,
	0x39, 0xfd, 0xe7, 0x55, 0x41, 0x13, 0xb3, 0x4b, 0x47, 0x6b, 0xd8, 0xae, 0xd0, 0xbf, 0x38, 0xa7,
	0x58, 0xdc, 0x52, 0xbc, 0xee, 0xa0, 0xe9, 0x4b, 0x2f, 0xd8, 0x41, 0x33, 0x78, 0x1b, 0x8e, 0x27,
	0x83, 0x8f, 0xa5, 0xa4, 0x2d, 0x37, 0xb3, 0x5e, 0x5d, 0xa9, 0x7c, 0xde, 0xde, 0xed, 0x25, 0xf3,
	0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xb8, 0xea, 0xa0, 0x53, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SandboxClient is the client API for Sandbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SandboxClient interface {
	Compile(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
}

type sandboxClient struct {
	cc *grpc.ClientConn
}

func NewSandboxClient(cc *grpc.ClientConn) SandboxClient {
	return &sandboxClient{cc}
}

func (c *sandboxClient) Compile(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/proto.Sandbox/compile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServer is the server API for Sandbox service.
type SandboxServer interface {
	Compile(context.Context, *Input) (*Output, error)
}

func RegisterSandboxServer(s *grpc.Server, srv SandboxServer) {
	s.RegisterService(&_Sandbox_serviceDesc, srv)
}

func _Sandbox_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sandbox/Compile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Compile(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sandbox_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sandbox",
	HandlerType: (*SandboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "compile",
			Handler:    _Sandbox_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox.proto",
}
